# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_capture.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog_capture(object):
    def setupUi(self, Dialog_capture):
        Dialog_capture.setObjectName("Dialog_capture")
        Dialog_capture.resize(510, 382)
        self.layoutWidget = QtWidgets.QWidget(Dialog_capture)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 491, 361))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.layoutWidget)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("btn_cap")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName("btn_save")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog_capture)
        QtCore.QMetaObject.connectSlotsByName(Dialog_capture)

    def retranslateUi(self, Dialog_capture):
        _translate = QtCore.QCoreApplication.translate
        Dialog_capture.setWindowTitle(_translate("Dialog_capture", "Screen capture"))
        self.pushButton_2.setText(_translate("Dialog_capture", "Chụp"))
        self.pushButton_3.setText(_translate("Dialog_capture", "Lưu"))
