# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_kill.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog_kill(object):
    def setupUi(self, Dialog_Kill):
        Dialog_Kill.setObjectName("Dialog_Kill")
        Dialog_Kill.resize(389, 50)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_Kill.sizePolicy().hasHeightForWidth())
        Dialog_Kill.setSizePolicy(sizePolicy)
        self.layoutWidget = QtWidgets.QWidget(Dialog_Kill)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 371, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.btn_kill = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_kill.setObjectName("btn_kill")
        self.horizontalLayout.addWidget(self.btn_kill)

        self.retranslateUi(Dialog_Kill)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Kill)

    def retranslateUi(self, Dialog_Kill):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Kill.setWindowTitle(_translate("Dialog_Kill", "Kill"))
        self.btn_kill.setText(_translate("Dialog_Kill", "Kill"))
