# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_keystroke.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog_keystroke(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(506, 359)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 481, 341))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_hook = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_hook.setObjectName("btn_hook")
        self.horizontalLayout_2.addWidget(self.btn_hook)
        self.btn_unhook = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_unhook.setObjectName("btn_unhook")
        self.horizontalLayout_2.addWidget(self.btn_unhook)
        self.btn_key = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_key.setObjectName("btn_key")
        self.horizontalLayout_2.addWidget(self.btn_key)
        self.btn_delete = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_delete.setObjectName("btn_delete")
        self.horizontalLayout_2.addWidget(self.btn_delete)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.layoutWidget)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout.addWidget(self.textBrowser_2, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Key stroke"))
        self.btn_hook.setText(_translate("Dialog", "Hook"))
        self.btn_unhook.setText(_translate("Dialog", "Unhook"))
        self.btn_key.setText(_translate("Dialog", "In phím"))
        self.btn_delete.setText(_translate("Dialog", "Xóa"))
