# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog_main(object):
    def setupUi(self, dialog_main):
        dialog_main.setObjectName("dialog_main")
        dialog_main.resize(337, 315)
        dialog_main.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(dialog_main)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_key = QtWidgets.QPushButton(dialog_main)
        self.btn_key.setObjectName("btn_key")
        self.gridLayout.addWidget(self.btn_key, 3, 0, 1, 1)
        self.btn_re = QtWidgets.QPushButton(dialog_main)
        self.btn_re.setObjectName("btn_re")
        self.gridLayout.addWidget(self.btn_re, 4, 0, 1, 1)
        self.btn_cap = QtWidgets.QPushButton(dialog_main)
        self.btn_cap.setObjectName("btn_cap")
        self.gridLayout.addWidget(self.btn_cap, 5, 0, 1, 1)
        self.btn_exit = QtWidgets.QPushButton(dialog_main)
        self.btn_exit.setObjectName("btn_exit")
        self.gridLayout.addWidget(self.btn_exit, 7, 0, 1, 1)
        self.btn_shutdown = QtWidgets.QPushButton(dialog_main)
        self.btn_shutdown.setObjectName("btn_shutdown")
        self.gridLayout.addWidget(self.btn_shutdown, 6, 0, 1, 1)
        self.btn_process = QtWidgets.QPushButton(dialog_main)
        self.btn_process.setObjectName("btn_process")
        self.gridLayout.addWidget(self.btn_process, 1, 0, 1, 1)
        self.btn_app = QtWidgets.QPushButton(dialog_main)
        self.btn_app.setObjectName("btn_app")
        self.gridLayout.addWidget(self.btn_app, 2, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(dialog_main)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.btn_connect = QtWidgets.QPushButton(dialog_main)
        self.btn_connect.setObjectName("btn_connect")
        self.horizontalLayout.addWidget(self.btn_connect)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label = QtWidgets.QLabel(dialog_main)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(dialog_main)
        QtCore.QMetaObject.connectSlotsByName(dialog_main)

    def retranslateUi(self, dialog_main):
        _translate = QtCore.QCoreApplication.translate
        dialog_main.setWindowTitle(_translate("dialog_main", "Main"))
        self.btn_key.setText(_translate("dialog_main", "Keystroke"))
        self.btn_re.setText(_translate("dialog_main", "Sửa registry"))
        self.btn_cap.setText(_translate("dialog_main", "Chụp màn hình"))
        self.btn_exit.setText(_translate("dialog_main", "Thoát"))
        self.btn_shutdown.setText(_translate("dialog_main", "Tắt máy"))
        self.btn_process.setText(_translate("dialog_main", "Processing running"))
        self.btn_app.setText(_translate("dialog_main", "App running"))
        self.btn_connect.setText(_translate("dialog_main", "Kết nối"))
        self.label.setText(_translate("dialog_main", "No Connection"))
